site_name: planning-data-science
theme:
  name: material
  icon:
    logo: material/map-legend
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
nav:
  - Home: index.md
  - Basics:
      - 101: examples/basics_101.ipynb
      - 202: examples/read_with_pandas.ipynb
  - Work with Files:
      - Read non-spatial data: examples/read_with_pandas.ipynb
      - Read spatial data: examples/geopandas.ipynb
  - Work with Databases:
      - .env file: examples/environment_variables.ipynb
      
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
