site_name: planning-data-science
theme:
  name: material
  icon:
    logo: material/map-legend
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
nav:
  - Home: index.md
  - Basics:
      - 101: examples/basics/python_101.ipynb
      - 202: examples/basics/python_202.ipynb
  - Libraries:
      - pandas: examples/libraries/pandas.ipynb
      - geopandas: examples/libraries/geopandas.ipynb
  - Databases:
      - .env file: examples/databases/dotenv.ipynb
      - psycopg2: examples/databases/psycopg2.ipynb
      - sqlalchemy: examples/databases/sqlalchemy.ipynb

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
