site_name: planning-data-science
theme:
  name: material
  icon:
    logo: material/map-legend
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
nav:
  - Home: index.md
  - Tabular data:
      - Read from file: examples/read_with_pandas.ipynb
      - Write to file: examples/script.py

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
